### ISSUE TITLE
Signed integer overflow in nmd_assembly.h at lines 7715 and 7842

### ISSUE THREAD

**Issue by fuzzah** [Nomade040/nmd#10]
There are two places in nmd_assembly.h that introduce **undefined behavior**:

### nmd_assembly.h:7715:81: runtime error: signed integer overflow: 2147483647 + 5 cannot be represented in type 'int'
relevant code part:
```
(int64_t)((int32_t)(si->instruction->immediate) + (int32_t)(si->instruction->length))
```
The field **immediate** is uint64_t, **length** is uint8_t.
Hard to understand real intention here, but my _naive_ fix would look like this:
```
(int64_t)(si->instruction->immediate + si->instruction->length)
```
Small reproducer (contents of buffer in examples/assembly_example.c):
[int_overflow_in_nmd_assembly_h__line_7715.tar.gz](https://github.com/Nomade040/nmd/files/6137667/int_overflow_in_nmd_assembly_h__line_7715.tar.gz)
(to get runtime error message, compile with clang and use flag --fsanitize=undefined)
 
 
### nmd_assembly.h:7842:64: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
relevant code part:
```
1 << (si->instruction->disp_mask * 8 - 1)
```
Easily fixable by changing the first 1 to 1U:
```
1U << (si->instruction->disp_mask * 8 - 1)
```

**Comment by Nomade040** [comment]
I believe the issue should be fixed by commits 567a471 and 239fcf8.
