### ISSUE TITLE
(Memory) Patch(), Write(), Nop() and other functions that write to memory should have a parameter to unprotect the relevant page(s) 

### ISSUE THREAD

**Issue by RibShark** [Nomade040/nmd#2]
Obviously, writing to memory that is protected is not possible, so the library should (at least have the option to) unprotect the relevant pages when writing to such memory. Ideally the protection value should be reset once all data is written to memory.

**Comment by Nomade040** [comment]
The Patch() and Nop() member functions of MemEx and MemIn rely on Write().

Write() checks if the memory is not writable(what do you consider "protected"?) and changes the protection, then it restores the old protection.

I don't understand, could you explain it in another way or provide examples?

**Comment by RibShark** [comment]
Ah, didn't look closely enough at the implementation. The issue here is that I was trying to write to a page with the protection PAGE_EXECUTE_READ, which wasn't included in the code that detects write protection.
