### ISSUE TITLE
(Memory) PatternScan Deadlock

### ISSUE THREAD

**Issue by RibShark** [Nomade040/nmd#4]
When using PatternScan() in memory the threads created never finish executing, causing the executable to get stuck at thread.join();
I am using MemIn, but I would guess the same bug happens with MemEx. My compiler is VS2019.

**Comment by Nomade040** [comment]
I could not reproduce the issue on my side, could you provide the part of the code that's causing it?

**Comment by RibShark** [comment]
```// dllmain.cpp : Defines the entry point for the DLL application.
#include "pch.h"
#define NMD_MEMORY_IMPLEMENTATION
#include "external/nmd_memory.hpp"

float fInvAspectRatio = 9.0f / 16.0f; // temp for testing

extern "C" __declspec(dllexport) void InitializeASI() {
    auto _2DspriteHookAddr = MemIn::AOBScan("D8 0D ? ? ? ? D9 01", ScanBoundaries(SCAN_BOUNDARIES::ALL_MODULES)); // 0x4771C3 on multilanguage EXE
    MemIn::Write<float*>(_2DspriteHookAddr + 2, &fInvAspectRatio);
}

bool isUALPresent = true; // temp for testing

BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID lpReserved)
{
    if (reason == DLL_PROCESS_ATTACH)
    {
        if (!isUALPresent) { InitializeASI(); }
    }
    return TRUE;
}
```
Here's a simple test case where I attempt to write to an address returned by the AOBScan (which when called gets stuck in PatternScan at thread.join). This is compiled into a DLL that is then injected into the game via ASI loader, which simply loads the library and calls InitializeASI().

I tried manually editing the code in PatternScan to do everything in a single thread and create no others, and it works fine then, so I'm really not sure what's going on here.

**Comment by Nomade040** [comment]
I believe the issue is not in the library.

Take a look at this page: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices

It says "Improper synchronization within DllMain can cause an application to deadlock or access data or code in an uninitialized DLL. Calling certain functions from within DllMain causes such problems.".

You may create a thread in order to call InitializeASI like this:
![image](https://user-images.githubusercontent.com/31376198/80891995-1697f400-8c9e-11ea-9f88-0771d7115994.png)

**Comment by RibShark** [comment]
> It says "Improper synchronization within DllMain can cause an application to deadlock or access data or code in an uninitialized DLL. Calling certain functions from within DllMain causes such problems.".

DllMain isn't calling InitializeASI() in my code, as "isUALPresent" is false (the call was only there for debugging purposes anyhow). InitializeASI() is being called by the ASI Loader which does so in a proper manner.
