### ISSUE TITLE
Are you the author of ArmaFP?

### ISSUE THREAD

**Issue by mrexodia** [Nomade040/nmd#5]
I remember reverse engineering how that worked and it had a very similar looking length disassembler to yours.

**Comment by Nomade040** [comment]
No, sorry I never heard of this project. I developed the length disassembler by checking how each instruction is supposed to be parsed in Intel's SDM Volume 2 Appendix A(opcode map). I guess they look similar because we might have taken a similar approach to make a length disassembler.

**Comment by mrexodia** [comment]
Thanks!
